apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev
  region: ap-southeast-1

nodeGroups:
  - name: ng-1
    availabilityZones: ["ap-southeast-1a"]
    minSize: 2
    maxSize: 2
    instancesDistribution:
        instanceTypes: ["t3a.2xlarge"]
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        